name: .NET CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    
    - name: List directory contents
      run: |
        pwd
        ls -la
        find . -name "*.sln"
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      shell: bash
      run: |
        chmod +x ./Health\&Med.sln
        dotnet restore "./Health\&Med.sln"
      
    - name: Build
      shell: bash
      run: dotnet build "./Health\&Med.sln" --no-restore
      
    - name: Test
      shell: bash
      run: dotnet test "./Health\&Med.sln" --no-build --verbosity normal